### PR TITLE
Fix style2

### PR DESCRIPTION
**Pull request by Dirk-Sandberg**
Moved the main screen into its own .py and .kv files, and made your `MainApp` class create the `ScreenManager` in kv code directly. In my opinion, this is how I would set up the project if it were my own, but you certainly don't have to go this route if it doesn't feel right to you :)

### CODE REVIEW

**Review by JLugarEE — COMMENTED** [review]
Wow, this is totally the most I would expect. Meaning you went above and beyond the request to what I thought I could do on my own from the first option. I appreciate your informative comments. I hope 2021, brings you more work.

**Comment by Dirk-Sandberg** [comment]
@JLugarEE My bad, I was running the wrong code to test this while I was working on it. My latest commit changed your references from `app.sm` to `app.root` to reference the ScreenManager. 

In my method, I have the ScreenManager widget as the "root" widget of the app, which is basically the very first widget which all other widgets are added under. For example, the root widget is the ScreenManager, the direct children of the ScreenManager are the Screens, and you have buttons, labels, layouts, etc. all under your Screens. In a hierarchical sense, the root widget is the one at the very top.

The ScreenManager has been instantiated in `main.kv`, and since this is the .kv file associated with your `MainApp` class, the ScreenManager has become the "root" widget for your app, allowing you to reference it very handily using `app.root` in kv code, or similarly `App.get_running_app().root` in Python code. 

Using this method, you don't have to mess around with ObjectProperties in python, or try to create any parts of the interface in Python (like creating a ScreenManager and adding it to your app) - that's all done in kv, and that's exactly what the kv language is designed for.

**Comment by JLugarEE** [comment]
Erik, again blown away by your explanations and solutions. Thank you for your explicit, direct and clear guidance. Keep up this excellence it will make you rise well and far, just be patient. Results may lag our eagerness at times. Again thank you.

**Comment by JLugarEE** [comment]
Very Awesome! I merely had to sync the git local repo with the fix-style2 fix, update req'ts "pip install -r requirements.txt", save these req'ts for managing my VENV via "pip freeze > sndbrgReqts.txt" just my style. And it works like a charm! Now to finish merge.

New bonus, I'm fighting less to understand GIT. Now, to wrap my head around these lessons. So, very, very grateful.

**Pull request closed without merging**
